### ISSUE TITLE
Making a Docker container

### ISSUE THREAD

**Issue by turbcool** [heliomar-pena/nsfw-proxy#1]
Would you consider creating a Docker container for your tool?

**Comment by heliomar-pena** [comment]
Hi!, I added the Dockerfiles to the tool on [dev branch](https://github.com/heliomar-pena/nsfw-proxy/tree/dev) and pushed the images to [dockerhub](https://hub.docker.com/r/heliomarpena/nsfw_proxy/tags). Here are the [instructions to run it](https://github.com/heliomar-pena/nsfw-proxy/tree/dev?tab=readme-ov-file#run-it-first-time-pull-the-image-create-a-container-configure-ports-and-volumes-if-needed), please try it if you can and let me know if works for you.

Also say me if you have any suggestion about the implementation
