### ISSUE TITLE
Here to say thanks!

### ISSUE THREAD

**Issue by mwalid207** [heliomar-pena/nsfw-proxy#4]
Salam , **heliomar** 
I have been searching for maybe 6 months and tried to devlop my own solution after this long period of  searching (I'm not very good in programing but can do somethings) , But I'm very happy that you working on this because I'm also working on the same. 
Maybe some PRs from me will be here soon.

**Thanks a lot , Best wishes.**

**Comment by heliomar-pena** [comment]
Thank you @mwalid207 :) Please let me know if you have any problem in the installation or need any help. Any doubt just ping me.

BTW I am currently working on Dockerize it to make easier the installation https://github.com/heliomar-pena/nsfw-proxy/issues/2
